[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E", "F", "I"]

[tool.ruff.lint.isort]
known-first-party = ["controllers", "core", "models", "services", "ui", "utils"]
combine-as-imports = true
force-sort-within-sections = true